<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>OrderedClicker.Mac</AssemblyName>
    <Version>2.1.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>../../installer/assets/ordered-clicker.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OrderedClicker.Shared/OrderedClicker.Shared.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.7" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.7" />
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>
</Project>
